// action types
const facetTypes = {
  FETCH_FACETS_SUCCESS: "FETCH_FACETS_SUCCESS",
  FETCH_FACETS_UPDATE: "FETCH_FACETS_UPDATE",
  FETCH_FACETS_FAILURE: "FETCH_FACETS_FAILURE",
};

export default facetTypes;
