const pageTypes = {
    FETCH_PAGEDATA_SUCCESS: "FETCH_PAGEDATA_SUCCESS",
    UPDATE_PAGEDATA_PAGESIZE: "UPDATE_PAGEDATA_PAGESIZE",
    UPDATE_PAGEDATA_NEXT: "UPDATE_PAGEDATA_NEXT",
    UPDATE_PAGEDATA_PREV: "UPDATE_PAGEDATA_PREV"
};

export default pageTypes;