const tableTypes = {
    FETCH_TABLECOLS_REQUEST: "FETCH_TABLECOLS_REQUEST",
    FETCH_TABLECOLS_SUCCESS: "FETCH_TABLECOLS_SUCCESS",
    UPDATE_TABLECOLS_SUCCESS: "UPDATE_TABLECOLS_SUCCESS",
    FETCH_TABLECOLS_FAILURE: "FETCH_TABLECOLS_FAILURE",
    UPDATE_TABLECOLS_FAILURE: "UPDATE_TABLECOLS_FAILURE",
  };
  
  export default tableTypes;
  