//action types
export const runtimeTypes = {
  FETCH_RUNTIME_REQUEST: "FETCH_RUNTIME_REQUEST:",
  FETCH_RUNTIME_SUCCESS: "FETCH_RUNTIME_SUCCESS",
  FETCH_RUNTIME_UPDATE: "FETCH_RUNTIME_UPDATE",
  TOGGLE_RUNTIME_SELECT: "TOGGLE_RUNTIME_SELECT",
  FETCH_RUNTIME_FAILURE: "FETCH_RUNTIME_FAILURE",
  ADD_RUNTIME_HIDDENCOLS: "ADD_RUNTIME_HIDDENCOLS",
  REMOVE_RUNTIME_HIDDENCOLS: "REMOVE_RUNTIME_HIDDENCOLS",
  INITIALIZE_COLUMN_SORT: "INITIALIZE_COLUMN_SORT",
  CHANGE_COLUMN_SORT: "CHANGE_COLUMN_SORT"
};
