//action types
export const runtimeTypes = {
  FETCH_RUNTIME_REQUEST: "FETCH_RUNTIME_REQUEST:",
  FETCH_RUNTIME_SUCCESS: "FETCH_RUNTIME_SUCCESS",
  FETCH_RUNTIME_UPDATE: "FETCH_RUNTIME_UPDATE",
  TOGGLE_RUNTIME_SELECT: "TOGGLE_RUNTIME_SELECT",
  FETCH_RUNTIME_FAILURE: "FETCH_RUNTIME_FAILURE",
};
